In [2]:
import numpy as np

In [3]:
array1 = np.array([3,4,5])
array1.ndim

1

In [4]:
np.arange(2,10,2)

array([2, 4, 6, 8])

In [5]:
array1.shape

(3,)

In [6]:
array4 = np.full(5, "merhaba")
array4

array(['merhaba', 'merhaba', 'merhaba', 'merhaba', 'merhaba'], dtype='<U7')

In [7]:
array2 = np.linspace(num=5,endpoint=True,start=1,stop=6)
array2

array([1.  , 2.25, 3.5 , 4.75, 6.  ])

In [8]:
array3 = np.random.randint(1,100,size=(5,5))
array3

array([[69, 32, 69, 28, 75],
       [11, 53, 17, 81, 51],
       [71,  1, 56,  1, 15],
       [ 7, 55, 27, 30, 47],
       [30, 49, 19, 13, 56]])

In [9]:
customArray = np.array([[[1,2,3], [4,5,6]],[[7,8,9],[10,11,12]]])
print("derinlik :", customArray.shape[0])
print("satır :", customArray.shape[1])
print("sütun :", customArray.shape[2])

derinlik : 2
satır : 2
sütun : 3


In [10]:
customArray

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [11]:
customArray[0:2,1,0]

array([ 4, 10])

In [12]:
customArray = customArray.astype(np.float32)
customArray.dtype

dtype('float32')

In [13]:
array = np.array([1,2,3,4,5,6])
carray=array.copy()  #bellekte yeni alan açar
varray = array.view() #orijinal versiyonu da değiştirir
array,carray,varray

(array([1, 2, 3, 4, 5, 6]),
 array([1, 2, 3, 4, 5, 6]),
 array([1, 2, 3, 4, 5, 6]))

In [14]:
array[1] = 444
carray[0] = 999
varray[0] = 555

array,carray,varray

(array([555, 444,   3,   4,   5,   6]),
 array([999,   2,   3,   4,   5,   6]),
 array([555, 444,   3,   4,   5,   6]))

In [15]:
a = np.array([[[1, 2, 3]]])

b = np.squeeze(a)

print("Orjinal dizi:")
print(a)
print("Sıkıştırılmış dizi:")
print(b)

Orjinal dizi:
[[[1 2 3]]]
Sıkıştırılmış dizi:
[1 2 3]
