In [78]:
import numpy as np

array1 = np.array([1,2,3,4,5,6,7,8])
array2 = np.array([[1,2,3,4], [5,6,7,8]])

In [79]:
array1.shape, array2.shape

((8,), (2, 4))

In [80]:
arrayOneToTwo = array1.reshape(2,4)
arrayOneToTwo, arrayOneToTwo.shape

(array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 (2, 4))

In [81]:
arrayTwoToThree = array2.reshape(2,2,2)
arrayTwoToThree, arrayTwoToThree.shape

(array([[[1, 2],
         [3, 4]],
 
        [[5, 6],
         [7, 8]]]),
 (2, 2, 2))

In [82]:
#iterasyon işlemleri
array3 = np.array([[[1,2,3], [4,5,6]],
                   [[7,8,9], [10,11,12]]])

array3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [83]:
for i,eleman in enumerate(array1):
  print(f"{i+1}.eleman : {eleman}")

1.eleman : 1
2.eleman : 2
3.eleman : 3
4.eleman : 4
5.eleman : 5
6.eleman : 6
7.eleman : 7
8.eleman : 8


In [84]:
for eleman in array2:
  for eleman2 in eleman:
    print(eleman2)

1
2
3
4
5
6
7
8


In [85]:
for eleman in array3:
  for eleman2 in eleman:
    for eleman3 in eleman2:
      print(eleman3)

1
2
3
4
5
6
7
8
9
10
11
12


In [86]:
for i in np.nditer(array3):
  print(i)

1
2
3
4
5
6
7
8
9
10
11
12


In [87]:
for i,eleman in np.ndenumerate(array3):
  print(f"{i}.eleman: {eleman}")

(0, 0, 0).eleman: 1
(0, 0, 1).eleman: 2
(0, 0, 2).eleman: 3
(0, 1, 0).eleman: 4
(0, 1, 1).eleman: 5
(0, 1, 2).eleman: 6
(1, 0, 0).eleman: 7
(1, 0, 1).eleman: 8
(1, 0, 2).eleman: 9
(1, 1, 0).eleman: 10
(1, 1, 1).eleman: 11
(1, 1, 2).eleman: 12


In [88]:
array01 = np.array([[1,2],
                    [3,4]])
array02 = np.array([[5,6],
                    [7,8]])
np.concatenate((array01,array02))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [89]:
np.vstack((array01,array02)),np.hstack((array01,array02))

(array([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]]),
 array([[1, 2, 5, 6],
        [3, 4, 7, 8]]))

In [90]:
np.stack((array01,array02),axis=1)

array([[[1, 2],
        [5, 6]],

       [[3, 4],
        [7, 8]]])

In [91]:
ar1 = np.array([1,2,3,4,5,5])
ar2 = np.array([[1,2],[3,4],[5,6],[7,8]])
np.array_split(ar1,3)[0][0]

1

In [99]:
#Search işlemleri
print(np.where(ar1==5)[0])

[4 5]


In [100]:
#Sorting işlemleri
a1 = np.array([3,2,4,1,2,3,4,7,8,9,4])
a2 = np.array(["Efe","Ceyda","Ayşe","Ozan","Ahmet"])
ar3 = np.array([True,False,False,True])

In [104]:
np.sort(a1,kind="quicksort")[::-1],np.sort(a2,kind="mergesort"),np.sort(ar3,kind="heapsort")

(array([9, 8, 7, 4, 4, 4, 3, 3, 2, 2, 1]),
 array(['Ahmet', 'Ayşe', 'Ceyda', 'Efe', 'Ozan'], dtype='<U5'),
 array([False, False,  True,  True]))