In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split,GridSearchCV
from sklearn.linear_model import LinearRegression,Ridge,Lasso,ElasticNet
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score,mean_absolute_error

In [ ]:
housing=fetch_california_housing()
data=pd.DataFrame(housing.data,columns=housing.feature_names)
X=housing.data
y=housing.target

In [ ]:
X,y

(array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
           37.88      , -122.23      ],
        [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
           37.86      , -122.22      ],
        [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
           37.85      , -122.24      ],
        ...,
        [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
           39.43      , -121.22      ],
        [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
           39.43      , -121.32      ],
        [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
           39.37      , -121.24      ]]),
 array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894]))

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X=scaler.fit_transform(X)
X

array([[ 2.34476576,  0.98214266,  0.62855945, ..., -0.04959654,
         1.05254828, -1.32783522],
       [ 2.33223796, -0.60701891,  0.32704136, ..., -0.09251223,
         1.04318455, -1.32284391],
       [ 1.7826994 ,  1.85618152,  1.15562047, ..., -0.02584253,
         1.03850269, -1.33282653],
       ...,
       [-1.14259331, -0.92485123, -0.09031802, ..., -0.0717345 ,
         1.77823747, -0.8237132 ],
       [-1.05458292, -0.84539315, -0.04021111, ..., -0.09122515,
         1.77823747, -0.87362627],
       [-0.78012947, -1.00430931, -0.07044252, ..., -0.04368215,
         1.75014627, -0.83369581]])

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [ ]:
alphas=[0.01,0.1,0.5]
l1_ratios=[0.2,0.5,0.8]
#1 e yaklaştıkça lassoya , 0 a yaklaştıkça ridge'e ağırlık veriyor

for alpha in alphas:
  for l1_ratio in l1_ratios:
    model=ElasticNet(alpha=alpha,l1_ratio=l1_ratio)
    model.fit(x_train,y_train)
    y_pred=model.predict(x_test)

    mse=mean_squared_error(y_test,y_pred)
    mae=mean_absolute_error(y_test,y_pred)
    r2=r2_score(y_test,y_pred)
    selected_features=data.columns[model.coef_!=0]

    print(f"L1 ratio={l1_ratio}")
    print(f"alpha={alpha},mse={mse},mae={mae} r2={r2}")
    print(f"Seçilen Özellikler : {selected_features}")

L1 ratio=0.2
alpha=0.01,mse=0.5510110427948043,mae=0.5336421384228245 r2=0.5795121584602659
Seçilen Özellikler : Index(['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'AveOccup', 'Latitude',
       'Longitude'],
      dtype='object')
L1 ratio=0.5
alpha=0.01,mse=0.5495847965164322,mae=0.5341801453569646 r2=0.5806005562826668
Seçilen Özellikler : Index(['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'AveOccup', 'Latitude',
       'Longitude'],
      dtype='object')
L1 ratio=0.8
alpha=0.01,mse=0.5484609922720293,mae=0.5349085320231953 r2=0.5814581543784244
Seçilen Özellikler : Index(['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'AveOccup', 'Latitude',
       'Longitude'],
      dtype='object')
L1 ratio=0.2
alpha=0.1,mse=0.6012225997661987,mae=0.5751717005116809 r2=0.541194688261917
Seçilen Özellikler : Index(['MedInc', 'HouseAge', 'AveBedrms', 'AveOccup', 'Latitude', 'Longitude'], dtype='object')
L1 ratio=0.5
alpha=0.1,mse=0.6357612809406279,mae=0.5969669331767173 r2=0.5148375114202305


Lasso Regresyonu : özellikle multicollinearity sorunları olan ve çok sayıda değişken içeren veri setlerinde tercih edilir.Değişken seçimi yapar.

Elastic Net Regresyonu : Ridge ve Lasso regresyonlarının en iyi özelliklerini hibritler.İki farklı düzenleme parametresine sahip.

Random Forest Regresyonu : Farklı veri türlerini yönetme ve karar ağaçlarının gücünü ortaya koyarak güçlü ve esnek bir model sunar.

Ridge Regresyonu : çoklu doğrusal regresyon modellerinde overfitting sorununu çözmek ve modellemede genellemeyi artırmak için kullanılır Düzenleme parametresi alfadır.Scaling yapılırsa daha iyi performans verir